# Generated by Django 4.1.4 on 2023-01-01 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_tag_id_product_tag_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='order',
        ),
    ]
